# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  # Brthrs Vagrant Box

  # Box
  config.vm.box = "brthrs/brthrs-vagrant-box"

  # Private Network with Hostsupdater (https://github.com/cogitatio/vagrant-hostsupdater)
  # config.vm.network :private_network, ip: "10.0.1.43"
  # config.vm.hostname = "brthrs.dev"
  # config.hostsupdater.aliases = ["brthrs.dev"]

  # Public Network
  config.vm.network "public_network"

  # Synced Folders
  config.vm.synced_folder "./", "/var/www/html", :owner => "www-data", :mount_options => [ "dmode=775", "fmode=774" ]

end